plugins:
  user_charts_enabled:
    default: true
    client: true

discourse_user_charts:
  user_charts_likes_multiplier:
    default: 0.1
    client: true
  user_charts_posts_multiplier:
    default: 1
    client: true
  user_charts_topics_multiplier:
    default: 2
    client: true
  user_charts_custom_field_one_enabled:
    default: false
    client: true
  user_charts_custom_field_one_name:
    default: ""
    client: true
  user_charts_custom_field_one_multiplier:
    default: 1
    client: true
  user_charts_custom_field_two_enabled:
    default: false
    client: true
  user_charts_custom_field_two_name:
    default: ""
    client: true
  user_charts_custom_field_two_multiplier:
    default: 1
    client: true
  user_charts_custom_field_three_enabled:
    default: false
    client: true
  user_charts_custom_field_three_name:
    default: ""
    client: true
  user_charts_custom_field_three_multiplier:
    default: 1
    client: true